#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
	bootstrap_before = 'config#before'
	bootstrap_after = 'config#after'
	colorscheme = 'gruvbox'
	colorscheme_bg = 'dark'

	enable_guicolors = true

	statusline_separator = 'arrow'
	statusline_iseparator = 'arrow'
	buffer_index_type = 4
	enable_tabline_filetype_icon = true
	enable_statusline_mode = false

	filemanager = 'defx'

	default_indent = 4
	expand_tab = false

# Enable autocomplete layer
[[layers]]
	name = 'autocomplete'
	auto_completion_return_key_behavior = 'smart'
	auto_completion_tab_key_behavior = 'smart'

[[layers]]
	name = 'shell'
	default_position = 'bottom'
	default_height = 30

[[layers]]
	name = 'git'
[[layers]]
	name = 'VersionControl'

[[layers]]
	name = 'sudo'

[[layers]]
	name = 'fzf'

[[custom_plugins]]
	repo = 'https://github.com/junegunn/fzf.vim'
	merged = false

[[custom_plugins]]
	repo = 'https://github.com/justinmk/vim-sneak'
	merged = false
